### ISSUE TITLE
My app is ready for review!

### ISSUE THREAD

**Issue by ageiduschek** [ageiduschek/codepath-simple-todo#1]
Thanks! @codepathreview @codepath

**Comment by nidhi1608** [comment]
Anna,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to <b>schedule a short 5-10 minute phone conversation</b> [here](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc). Navigate to [today's date and onward from there](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to include best number to reach you at to the invite? Look forward to chatting soon!

**Comment by nidhi1608** [comment]
Hi Anna,

Checking in to see if you would like to move forward with your application. Follow the next steps as mentioned in my comment above in case you missed it earlier. Admission is rolling, so the sooner you schedule, the better. Let us know if you have any questions in the mean time.

**Comment by ageiduschek** [comment]
Hi Nidhi!

So sorry I just saw this. Yes, I'm still interested in moving forward! I just signed up for phone call tomorrow. 

Talk to you soon,
Anna
